version: '3.5'

services:
    server:
        image: node:15-alpine
        container_name: 'nextjs-node'
        volumes:
            - .:/app
        ports:
            - '3111:3000'
        working_dir: '/app'
        command: 'npm start'
