name: E2E on Edge
on:
    push:
        branches:
            - main
jobs:
    cypress-run:
        runs-on: windows-latest
        # let's make sure our tests pass on Chrome browser
        name: E2E on Edge
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install deps and build
              run: |
                  npm install
                  npm run build
            - uses: cypress-io/github-action@v2
              with:
                  browser: edge
                  start: npm start
                  # quote the url to be safe against YML parsing surprises
                  wait-on: 'http://localhost:3111'
              env:
                  PORT: 3111
